/**
 * Post-removal verification of the ACTUAL generated clean output (byte level).
 *
 * Why this module exists:
 * The tool used to *claim* a clean result. Once a removal step had produced a
 * `cleanBlob`, the UI rendered a hardcoded "Privacy metadata remaining: 0"
 * without ever looking at the generated bytes. A JPEG whose removal path left
 * the privacy payload in place (the removal is a container rewrite, so an
 * unrecognised segment - a bare-TIFF APP1, an XMP block with a non-standard
 * namespace prefix, a padded APP13, ... - is copied through verbatim) was
 * therefore reported as verified clean even though the downloaded file still
 * carried the metadata.
 *
 * This module answers one question about the generated output only:
 * "does it still physically contain a privacy-bearing metadata container?".
 * It never looks at the input file, never at the pre-removal metadata object
 * and never at the removal result - the bytes are the source of truth.
 *
 * A finding does NOT produce a privacy field count. The count stays where it
 * belongs (the existing `filterMetadata()` classifier applied to a re-parse of
 * the same generated bytes). Findings only prevent the output from being
 * presented as verified clean, so an unverifiable container can never be
 * silently reported as "0 remaining".
 */

export interface VerificationFinding {
  /** Machine-readable id, e.g. 'jpeg-exif-segment'. */
  kind: string;
  /** English detail, for console diagnostics only. */
  detail: string;
}

/** JPEG metadata families the PRD removes (EXIF/XMP/IPTC/comments). */
const JPEG_EXIF_ID = ascii('Exif\u0000\u0000');
const JPEG_XMP_ID = ascii('http://ns.adobe.com/xap/1.0/');
const JPEG_XMP_EXT_ID = ascii('http://ns.adobe.com/xmp/extension/');
const JPEG_IPTC_ID = ascii('Photoshop 3.0\u0000');
/** Multi-picture container: carries no metadata field the classifier knows. */
const JPEG_MPF_ID = ascii('MPF\u0000');

/** Payload signatures searched for in the generated output's header region. */
const JPEG_PAYLOAD_SIGNATURES: ReadonlyArray<{ kind: string; detail: string; signature: readonly number[] }> = [
  { kind: 'jpeg-exif-payload', detail: 'EXIF payload ("Exif\\0\\0")', signature: JPEG_EXIF_ID },
  { kind: 'jpeg-xmp-payload', detail: 'XMP payload (http://ns.adobe.com/xap/1.0/)', signature: JPEG_XMP_ID },
  { kind: 'jpeg-xmp-extended-payload', detail: 'extended XMP payload', signature: JPEG_XMP_EXT_ID },
  { kind: 'jpeg-iptc-payload', detail: 'IPTC/Photoshop payload ("Photoshop 3.0")', signature: JPEG_IPTC_ID },
];

/**
 * Locate the EOI marker of an entropy-coded JPEG scan. Inside scan data a 0xFF
 * byte must be followed by 0x00 (stuffing), an RSTn marker or a new scan/segment
 * header, so the first unescaped FF D9 is the real end of image. Returns -1 when
 * the stream ends without one (mirrors the removal step, which throws instead).
 */
function findJpegEoiOffset(bytes: Uint8Array, from: number): number {
  let i = from;
  while (i + 1 < bytes.length) {
    if (bytes[i] !== 0xff) { i++; continue; }
    const marker = bytes[i + 1];
    if (marker === 0x00 || marker === 0x01 || marker === 0xff || (marker >= 0xd0 && marker <= 0xd7)) {
      i += 2;
      continue;
    }
    if (marker === 0xd9) return i;
    if (i + 3 >= bytes.length) return -1;
    const length = (bytes[i + 2] << 8) | bytes[i + 3];
    if (length < 2 || i + 2 + length > bytes.length) return -1;
    i += 2 + length;
  }
  return -1;
}

/** Where a JPEG segment-chain walk stopped. */
interface JpegWalkResult {
  /** Offset of the SOS/EOI marker the walk stopped at, or -1. */
  stopOffset: number;
  stoppedAtEoi: boolean;
}

/**
 * Walk one JPEG segment chain and record the privacy containers it still
 * contains. `strict` marks the walk of the file's own header chain (a
 * structural surprise there means the output cannot be verified); the walk of
 * post-EOI bytes is lenient because arbitrary trailer bytes are legal.
 */
function walkJpegChain(
  bytes: Uint8Array,
  start: number,
  findings: VerificationFinding[],
  strict: boolean,
): JpegWalkResult {
  const stop = (detail: string): JpegWalkResult => {
    if (strict) findings.push({ kind: 'jpeg-unverifiable-structure', detail });
    return { stopOffset: -1, stoppedAtEoi: false };
  };

  let pos = start;
  while (pos + 1 < bytes.length) {
    if (bytes[pos] !== 0xff) return stop('no marker prefix at byte ' + pos);
    const marker = bytes[pos + 1];

    if (marker === 0xd9) return { stopOffset: pos, stoppedAtEoi: true };
    if (marker === 0xda) return { stopOffset: pos, stoppedAtEoi: false };
    if (marker === 0x01 || (marker >= 0xd0 && marker <= 0xd8)) { pos += 2; continue; }
    if (marker === 0xff) { pos++; continue; }

    if (pos + 3 >= bytes.length) return stop('truncated segment header');
    const length = (bytes[pos + 2] << 8) | bytes[pos + 3];
    const segEnd = pos + 2 + length;
    if (length < 2 || segEnd > bytes.length) return stop('bad segment length at byte ' + pos);

    const payload = pos + 4;
    if (marker === 0xe1) {
      if (startsWith(bytes, payload, JPEG_EXIF_ID)) {
        findings.push({ kind: 'jpeg-exif-segment', detail: 'APP1 EXIF segment survived removal' });
      } else if (startsWith(bytes, payload, JPEG_XMP_ID) || startsWith(bytes, payload, JPEG_XMP_EXT_ID)) {
        findings.push({ kind: 'jpeg-xmp-segment', detail: 'APP1 XMP segment survived removal' });
      } else if (!startsWith(bytes, payload, JPEG_MPF_ID)) {
        // Multi-picture (e.g. Google Pixel) carries no PRD privacy family; every
        // other unrecognised APP1 payload may be an EXIF/XMP variant we cannot
        // read, so it must not pass as verified clean.
        findings.push({
          kind: 'jpeg-unrecognised-app1',
          detail: 'APP1 segment with an unrecognised payload survived removal',
        });
      }
    } else if (marker === 0xed) {
      findings.push(
        startsWith(bytes, payload, JPEG_IPTC_ID)
          ? { kind: 'jpeg-iptc-segment', detail: 'APP13 IPTC/Photoshop segment survived removal' }
          : { kind: 'jpeg-unrecognised-app13', detail: 'APP13 segment with an unrecognised payload survived removal' },
      );
    } else if (marker === 0xfe) {
      findings.push({ kind: 'jpeg-com-segment', detail: 'COM comment segment survived removal' });
    }

    pos = segEnd;
  }

  return stop('segment table ended without SOS/EOI');
}

/**
 * Walk the segment table of a generated JPEG (tolerant: a structural surprise
 * is reported instead of thrown) and collect every privacy-bearing container
 * that is still present. Scanning stops at the first SOS marker, because that
 * is where every client-side parser (and the removal step itself) stops
 * reading metadata.
 */
export function findJpegPrivacyFindings(bytes: Uint8Array): VerificationFinding[] {
  const findings: VerificationFinding[] = [];
  if (bytes.length < 4 || bytes[0] !== 0xff || bytes[1] !== 0xd8) {
    return [{ kind: 'jpeg-not-a-jpeg', detail: 'generated output is not a JPEG (missing SOI)' }];
  }

  const main = walkJpegChain(bytes, 2, findings, true);
  const headerEnd = main.stopOffset === -1 ? bytes.length : main.stopOffset;

  // A metadata segment can also be appended AFTER the EOI marker: the container
  // rewrite copies everything from EOI onwards verbatim and no client-side
  // parser reads past the scan data, so such a file would otherwise pass as
  // clean while still carrying its EXIF block. The trailer is walked too, but
  // silently - arbitrary bytes after EOI are legal in a JPEG.
  const eoiOffset = main.stopOffset !== -1 && !main.stoppedAtEoi
    ? findJpegEoiOffset(bytes, main.stopOffset + 2)
    : (main.stoppedAtEoi ? main.stopOffset : -1);
  if (eoiOffset !== -1 && eoiOffset + 2 < bytes.length && bytes[eoiOffset + 2] === 0xff) {
    walkJpegChain(bytes, eoiOffset + 2, findings, false);
  }

  // The chain walk cannot see a metadata block that was copied through inside
  // another segment's payload, so the header region is also searched for the
  // privacy payload signatures themselves.
  const alreadyFound = new Set(findings.map((f) => f.kind));
  for (const entry of JPEG_PAYLOAD_SIGNATURES) {
    if (alreadyFound.has(entry.kind)) continue;
    if (indexOfSignature(bytes, 2, headerEnd, entry.signature) !== -1) {
      findings.push({ kind: entry.kind, detail: entry.detail + ' still present in the generated output' });
    }
  }

  return findings;
}

function ascii(text: string): number[] {
  const out: number[] = [];
  for (let i = 0; i < text.length; i++) out.push(text.charCodeAt(i) & 0xff);
  return out;
}

function startsWith(bytes: Uint8Array, offset: number, signature: readonly number[]): boolean {
  if (offset < 0 || offset + signature.length > bytes.length) return false;
  for (let i = 0; i < signature.length; i++) {
    if (bytes[offset + i] !== signature[i]) return false;
  }
  return true;
}

/** Index of `signature` in [from, to) or -1. */
function indexOfSignature(bytes: Uint8Array, from: number, to: number, signature: readonly number[]): number {
  const limit = Math.min(to, bytes.length) - signature.length;
  for (let i = from; i <= limit; i++) {
    if (bytes[i] !== signature[0]) continue;
    let match = true;
    for (let j = 1; j < signature.length; j++) {
      if (bytes[i + j] !== signature[j]) { match = false; break; }
    }
    if (match) return i;
  }
  return -1;
}

const RIFF_ID = ascii('RIFF');
const WEBP_ID = ascii('WEBP');
/** RIFF chunks that only ever carry metadata the PRD removes. */
const WEBP_METADATA_CHUNKS: readonly string[] = ['EXIF', 'XMP ', 'XMP\u0000'];
const VP8X_FLAG_EXIF = 0x08;
const VP8X_FLAG_XMP = 0x04;

function readUint32LE(bytes: Uint8Array, offset: number): number {
  return (
    (bytes[offset] | (bytes[offset + 1] << 8) | (bytes[offset + 2] << 16) | (bytes[offset + 3] << 24)) >>> 0
  );
}

function readUint32BE(bytes: Uint8Array, offset: number): number {
  return (
    ((bytes[offset] << 24) | (bytes[offset + 1] << 16) | (bytes[offset + 2] << 8) | bytes[offset + 3]) >>> 0
  );
}

function readChunkId(bytes: Uint8Array, offset: number): string {
  return String.fromCharCode(bytes[offset], bytes[offset + 1], bytes[offset + 2], bytes[offset + 3]);
}

/**
 * Walk the RIFF chunk list of a generated WebP and report every surviving
 * metadata chunk plus any VP8X feature flag that still advertises EXIF/XMP.
 * Both EXIF layouts are container-identical, so no TIFF parsing is needed here.
 */
export function findWebpPrivacyFindings(bytes: Uint8Array): VerificationFinding[] {
  const findings: VerificationFinding[] = [];
  if (bytes.length < 12 || !startsWith(bytes, 0, RIFF_ID) || !startsWith(bytes, 8, WEBP_ID)) {
    return [{ kind: 'webp-not-a-webp', detail: 'generated output is not a RIFF/WEBP container' }];
  }

  const declaredEnd = Math.min(readUint32LE(bytes, 4) + 8, bytes.length);
  let offset = 12;

  while (offset + 8 <= declaredEnd) {
    const id = readChunkId(bytes, offset);
    const size = readUint32LE(bytes, offset + 4);
    const payloadEnd = offset + 8 + size;
    if (payloadEnd > bytes.length) {
      findings.push({ kind: 'webp-unverifiable-structure', detail: 'chunk "' + id + '" exceeds the file' });
      break;
    }
    if (WEBP_METADATA_CHUNKS.includes(id)) {
      findings.push({ kind: 'webp-metadata-chunk', detail: 'chunk "' + id + '" survived removal' });
    }
    if (id === 'VP8X' && size >= 1) {
      const flags = bytes[offset + 8];
      if ((flags & (VP8X_FLAG_EXIF | VP8X_FLAG_XMP)) !== 0) {
        findings.push({ kind: 'webp-vp8x-flags', detail: 'VP8X still advertises EXIF/XMP' });
      }
    }
    offset = payloadEnd + (size % 2);
  }

  return findings;
}

const PNG_SIGNATURE = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];

/** PNG metadata chunks: eXIf carries the EXIF/GPS block the PRD removes. */
const PNG_METADATA_CHUNKS: readonly string[] = ['eXIf'];

export function findPngPrivacyFindings(bytes: Uint8Array): VerificationFinding[] {
  const findings: VerificationFinding[] = [];
  if (bytes.length < 8 || !startsWith(bytes, 0, PNG_SIGNATURE)) {
    return [{ kind: 'png-not-a-png', detail: 'generated output is not a PNG (missing signature)' }];
  }

  let offset = 8;
  while (offset + 12 <= bytes.length) {
    const size = readUint32BE(bytes, offset);
    const type = readChunkId(bytes, offset + 4);
    const dataEnd = offset + 8 + size;
    if (dataEnd + 4 > bytes.length) {
      findings.push({ kind: 'png-unverifiable-structure', detail: 'chunk "' + type + '" exceeds the file' });
      break;
    }
    if (PNG_METADATA_CHUNKS.includes(type)) {
      findings.push({ kind: 'png-metadata-chunk', detail: 'chunk "' + type + '" survived removal' });
    }
    if (type === 'IEND') break;
    offset = dataEnd + 4;
  }

  return findings;
}

/**
 * Dispatch to the container scanner that matches the generated output's own
 * media type. TIFF returns no findings on purpose: the TIFF path is verified by
 * re-parsing the generated TIFF (exifr + the existing classifier) and
 * `stripTiffMetadata()` already re-reads its own output and throws if a single
 * non-structural tag survived.
 */
export function findOutputPrivacyFindings(bytes: Uint8Array, mimeType: string): VerificationFinding[] {
  const type = (mimeType || '').toLowerCase();
  if (type === 'image/jpeg' || type === 'image/jpg' || type === 'image/pjpeg') {
    return findJpegPrivacyFindings(bytes);
  }
  if (type === 'image/webp') return findWebpPrivacyFindings(bytes);
  if (type === 'image/png') return findPngPrivacyFindings(bytes);
  if (type === 'image/tiff' || type === 'image/tif') return [];
  return [{ kind: 'unverifiable-format', detail: 'no container scanner for "' + (mimeType || 'unknown') + '"' }];
}