/**
 * Post-removal output verification (P1 fix) - UI coverage.
 *
 * The audit finding this spec pins down:
 *   the UI rendered "Privacy metadata remaining: 0" from a hardcoded constant
 *   as soon as a removal step had produced a blob, without ever re-reading the
 *   generated output. A JPEG whose removal left the privacy payload in place
 *   (the audit's example: a "clean" output byte-identical to the source that
 *   still contained `Author=Jane Photographer`) was therefore reported as
 *   verified clean.
 *
 * What is proven here, always against the real generated bytes:
 *   TEST A - clean output: the removal really is clean, the displayed count is
 *            0 because an independent re-scan of the DOWNLOADED file says 0, and
 *            the download is only enabled after verification passed.
 *   TEST B - dirty output (real, unforced): a JPEG whose own EXIF block sits
 *            after the EOI marker is copied through verbatim, so the generated
 *            output is byte-identical to the source and still carries the
 *            privacy payload. The app must NOT claim 0 or success.
 *   TEST B2- dirty output (forced): the generated output bytes are forced to be
 *            the metadata-bearing source (the audit's premise), so the count
 *            shown must be the REAL count derived from those bytes - never 0.
 *   TEST C - TIFF regression, TEST D - WebP regression (unchanged removal).
 *   plus batch, async/stale-state and the six target viewports.
 *
 * Run with the dev server up: npx playwright test test-output-verification.spec.ts
 */
import { test, expect, type Page } from '@playwright/test';
import { mkdtempSync, writeFileSync, readFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import exifr from 'exifr';
import sharp from 'sharp';
// @ts-expect-error - plain ESM fixture builders shared with the Node harness
import {
  buildVerifiedCleanJpeg,
  buildTrailerExifJpeg,
  buildPlainJpeg,
  jpegChainMarkers,
  containsLatin1,
  privacyKeysInBytes,
  PRIVACY_VALUES,
} from './test-output-verification-fixture.mjs';
// @ts-expect-error - plain ESM fixture builders shared with the Node harness
import { buildMetadataRichTiff, PRIVACY_VALUES as TIFF_PRIVACY_VALUES } from './test-tiff-fixture.mjs';
// @ts-expect-error - plain ESM fixture builders shared with the Node harness
import {
  buildPrefixedExifWebp,
  buildMalformedWebp,
  chunkIds,
  readVp8x,
  leakedPrivacyValues,
} from './test-webp-fixture.mjs';

/** JPEG markers the removal contract promises to drop. */
const FORBIDDEN_JPEG_MARKERS = [0xe1, 0xed, 0xfe];

const VIEWPORTS = [
  { width: 375, height: 667, label: 'mobile-small' },
  { width: 390, height: 844, label: 'mobile-large' },
  { width: 768, height: 1024, label: 'tablet' },
  { width: 820, height: 1180, label: 'tablet-large' },
  { width: 1280, height: 800, label: 'laptop' },
  { width: 1440, height: 900, label: 'desktop' },
];

let workDir = '';
let cleanJpegPath = ''; // recognisable EXIF JPEG (removal can strip it)
let trailerJpegPath = ''; // audit shape: EXIF appended after EOI
let plainJpegPath = ''; // metadata-free: auto-strip produces a verifiable output
let cleanJpegBytes: Buffer = Buffer.alloc(0);
let trailerBytes: Buffer = Buffer.alloc(0);
let tiffPath = '';
let tiffBytes: Uint8Array = new Uint8Array(0);
let webpPath = '';
let webpBytes: Uint8Array = new Uint8Array(0);
let malformedWebpPath = '';

async function ensureReady(page: Page): Promise<void> {
  await page.waitForLoadState('networkidle');
  await page.waitForSelector('body[data-pmr-ready]', { timeout: 10000 });
}

/** The per-file status element that carries the verification result. */
function statusOf(page: Page, id: number) {
  return page.locator(`[data-id="${id}"] .text-xs`).first();
}

/**
 * Upload `file` and wait until the (auto-)removal of that upload reports
 * `expectedText`. Retries after a dev-server reload: Vite's dependency
 * re-optimization reloads the page, which wipes the tool's in-memory state and
 * would otherwise detach the freshly uploaded item mid-test. Every attempt
 * re-applies the same assertion, so a real failure still fails.
 */
async function uploadAndAwait(page: Page, file: string, expectedText: string): Promise<void> {
  let lastError: unknown;
  for (let attempt = 0; attempt < 3; attempt++) {
    await page.locator('#file-input').setInputFiles(file);
    try {
      await expect(page.locator('#files-list > div[data-id]')).toHaveCount(1, { timeout: 25000 });
      await expect(statusOf(page, 1)).toContainText(expectedText, { timeout: 25000 });
      return;
    } catch (err) {
      lastError = err;
      await page.waitForLoadState('domcontentloaded').catch(() => undefined);
    }
  }
  throw lastError;
}

test.beforeAll(async () => {
  workDir = mkdtempSync(join(tmpdir(), 'pmr-verify-'));

  cleanJpegBytes = await buildVerifiedCleanJpeg();
  writeFileSync((cleanJpegPath = join(workDir, 'verified-photo.jpg')), cleanJpegBytes);

  const trailer = await buildTrailerExifJpeg();
  trailerBytes = trailer.bytes;
  writeFileSync((trailerJpegPath = join(workDir, 'trailer-photo.jpg')), trailerBytes);

  writeFileSync((plainJpegPath = join(workDir, 'plain-photo.jpg')), await buildPlainJpeg());

  const icc = await sharp({ create: { width: 2, height: 2, channels: 3, background: { r: 1, g: 2, b: 3 } } })
    .tiff()
    .withMetadata({ icc: 'srgb' })
    .toBuffer();
  const iccBytes = (await sharp(icc).metadata()).icc;
  tiffBytes = buildMetadataRichTiff({ icc: iccBytes ? new Uint8Array(iccBytes) : null });
  writeFileSync((tiffPath = join(workDir, 'verified-photo.tiff')), tiffBytes);

  webpBytes = await buildPrefixedExifWebp({ width: 96, height: 64, alpha: true, icc: true });
  writeFileSync((webpPath = join(workDir, 'verified-photo.webp')), webpBytes);

  writeFileSync((malformedWebpPath = join(workDir, 'broken.webp')), buildMalformedWebp());
});

test.afterAll(() => {
  if (workDir) rmSync(workDir, { recursive: true, force: true });
});

test.describe('Post-removal verification of the generated output', () => {
  test('TEST A - clean JPEG: count comes from re-scanning the downloaded output', async ({ page }) => {
    await page.goto('http://localhost:4321/en');
    await ensureReady(page);

    await page.locator('#file-input').setInputFiles(cleanJpegPath);
    await expect(statusOf(page, 1)).toContainText('Privacy metadata found', { timeout: 30000 });

    // Nothing has been verified before the removal runs.
    await expect(statusOf(page, 1)).not.toContainText('Privacy metadata remaining');
    await expect(page.locator('#download-1')).toBeDisabled();

    await page.locator('#remove-1').click();
    await expect(page.locator('#remove-1')).toHaveText('✓ Success', { timeout: 30000 });
    await expect(statusOf(page, 1)).toContainText('Metadata removed successfully');
    await expect(statusOf(page, 1)).toContainText('Privacy metadata remaining: 0');

    // Download is only reachable once verification passed.
    const [download] = await Promise.all([
      page.waitForEvent('download'),
      page.locator('#download-1').click(),
    ]);
    expect(download.suggestedFilename()).toBe('verified-photo-clean.jpg');
    const saved = join(workDir, 'downloaded-clean.jpg');
    await download.saveAs(saved);

    // Independent re-scan of the DOWNLOADED bytes (not the app's own count).
    const downloaded = readFileSync(saved);
    const leakedKeys = await privacyKeysInBytes(downloaded, 'image/jpeg');
    expect(leakedKeys, `privacy keys still in the downloaded file: ${leakedKeys.join(', ')}`).toEqual([]);
    const forbidden = jpegChainMarkers(downloaded).filter((m) => FORBIDDEN_JPEG_MARKERS.includes(m));
    expect(forbidden.map((m) => m.toString(16)), 'no APP1/APP13/COM in the downloaded file').toEqual([]);
    for (const value of [...PRIVACY_VALUES, 'Exif', 'http://ns.adobe.com']) {
      expect(containsLatin1(downloaded, value), `downloaded file still contains "${value}"`).toBe(false);
    }
    // The displayed 0 equals the count derived from the downloaded bytes.
    const displayed = await statusOf(page, 1).textContent();
    expect(displayed).toContain(`Privacy metadata remaining: ${leakedKeys.length}`);
  });

  test('TEST B - dirty output: a byte-identical output that still carries EXIF is never claimed clean', async ({ page }) => {
    const warnings: string[] = [];
    page.on('console', (msg) => {
      if (msg.type() === 'warning') warnings.push(msg.text());
    });

    await page.goto('http://localhost:4321/en');
    await ensureReady(page);

    // The fixture's own EXIF block sits after EOI: the removal copies it through
    // verbatim, so the generated output is byte-identical to the source.
    expect(containsLatin1(trailerBytes, PRIVACY_VALUES[3]), 'fixture must carry the privacy payload').toBe(true);
    expect(Buffer.compare(readFileSync(trailerJpegPath), trailerBytes)).toBe(0);

    await page.locator('#file-input').setInputFiles(trailerJpegPath);
    await expect(page.locator('#files-list > div[data-id]')).toHaveCount(1, { timeout: 30000 });

    // The removal runs automatically; its output cannot be verified as clean.
    await expect(statusOf(page, 1)).toContainText('Verification failed', { timeout: 30000 });
    await expect(page.locator('#remove-1')).toHaveText('Try again');
    await expect(statusOf(page, 1)).not.toContainText('Metadata removed successfully');
    await expect(statusOf(page, 1)).not.toContainText('Privacy metadata remaining: 0');
    await expect(page.locator('#download-1')).toBeDisabled();
    await expect(page.locator('#processing-status')).toHaveClass(/hidden/);

    // The app inspected the real bytes and reported the surviving container.
    const containerWarning = warnings.find(
      (w) => w.includes('privacy container still present') && w.includes('jpeg-exif-segment'),
    );
    expect(containerWarning, `expected a surviving-EXIF-container warning, got: ${JSON.stringify(warnings)}`).toBeTruthy();
  });

  test('TEST B2 - forced dirty output: the real remaining count is reported, not 0', async ({ page }) => {
    // Force the generated output to be the metadata-bearing source, i.e. a
    // removal that leaves every privacy field in the output (the audit's
    // "byte-identical clean output" premise). Only the generated blob's byte
    // read is redirected; the verification, the parser and the classifier are
    // untouched, and the count is compared against an independent re-derivation
    // from those same bytes.
    const dirty = Array.from(cleanJpegBytes);
    await page.addInitScript((bytes: number[]) => {
      const original = Blob.prototype.arrayBuffer;
      const buffer = Uint8Array.from(bytes).buffer;
      Blob.prototype.arrayBuffer = function (this: Blob) {
        if (!(this instanceof File)) return Promise.resolve(buffer.slice(0));
        return original.call(this);
      };
    }, dirty);

    await page.goto('http://localhost:4321/en');
    await ensureReady(page);

    const expectedKeys = await privacyKeysInBytes(cleanJpegBytes, 'image/jpeg');
    expect(expectedKeys.length, 'forced dirty output must contain privacy fields').toBeGreaterThan(0);

    await page.locator('#file-input').setInputFiles(cleanJpegPath);
    await expect(statusOf(page, 1)).toContainText('Privacy metadata found', { timeout: 30000 });

    await page.locator('#remove-1').click();

    // The true count - derived from the generated bytes - must be displayed.
    await expect(statusOf(page, 1)).toContainText(`Privacy metadata remaining: ${expectedKeys.length}`, {
      timeout: 30000,
    });
    await expect(statusOf(page, 1)).toContainText('Verification failed');
    await expect(statusOf(page, 1)).not.toContainText('Metadata removed successfully');
    await expect(statusOf(page, 1)).not.toContainText('Privacy metadata remaining: 0');
    await expect(page.locator('#download-1')).toBeDisabled();
    await expect(page.locator('#remove-1')).toHaveText('Try again');
    await expect(page.locator('#processing-status')).toHaveClass(/hidden/);
  });

  test('TEST C - TIFF regression: removal still works and the generated TIFF is verified', async ({ page }) => {
    await page.goto('http://localhost:4321/en');
    await ensureReady(page);

    await page.locator('#file-input').setInputFiles(tiffPath);
    await expect(statusOf(page, 1)).toContainText('Privacy metadata found', { timeout: 30000 });

    await page.locator('#remove-1').click();
    await expect(page.locator('#remove-1')).toHaveText('✓ Success', { timeout: 30000 });
    await expect(statusOf(page, 1)).toContainText('Metadata removed successfully');
    await expect(statusOf(page, 1)).toContainText('Privacy metadata remaining: 0');

    const [download] = await Promise.all([
      page.waitForEvent('download'),
      page.locator('#download-1').click(),
    ]);
    expect(download.suggestedFilename()).toBe('verified-photo-clean.tiff');
    const saved = join(workDir, 'downloaded-clean.tiff');
    await download.saveAs(saved);

    // Independent re-scan of the DOWNLOADED TIFF (still a real TIFF).
    const downloaded = readFileSync(saved);
    expect(downloaded[0]).toBe(0x49);
    expect(downloaded[1]).toBe(0x49);
    expect(downloaded[2]).toBe(42);
    const leakedKeys = await privacyKeysInBytes(downloaded, 'image/tiff');
    expect(leakedKeys, `privacy keys still in the downloaded TIFF: ${leakedKeys.join(', ')}`).toEqual([]);
    for (const value of TIFF_PRIVACY_VALUES) {
      expect(containsLatin1(downloaded, value), `downloaded TIFF still contains "${value}"`).toBe(false);
    }
    const parsed = (await exifr.parse(Buffer.from(downloaded), { tiff: true, exif: true, gps: true })) || {};
    expect(parsed.Make).toBeUndefined();
    // The source fixture really did carry privacy metadata.
    expect(await privacyKeysInBytes(tiffBytes, 'image/tiff')).toContain('Make');
  });

  test('TEST D - WebP regression: removal keeps WebP and the generated WebP is verified', async ({ page }) => {
    await page.goto('http://localhost:4321/en');
    await ensureReady(page);

    await page.locator('#file-input').setInputFiles(webpPath);
    await expect(statusOf(page, 1)).toContainText('Privacy metadata found', { timeout: 30000 });

    await page.locator('#remove-1').click();
    await expect(page.locator('#remove-1')).toHaveText('✓ Success', { timeout: 30000 });
    await expect(statusOf(page, 1)).toContainText('Privacy metadata remaining: 0');

    const [download] = await Promise.all([
      page.waitForEvent('download'),
      page.locator('#download-1').click(),
    ]);
    expect(download.suggestedFilename()).toBe('verified-photo-clean.webp');
    const saved = join(workDir, 'downloaded-clean.webp');
    await download.saveAs(saved);

    // Independent re-scan of the DOWNLOADED WebP: still a WebP, EXIF/XMP gone.
    const downloaded = new Uint8Array(readFileSync(saved));
    expect(Buffer.from(downloaded.subarray(0, 4)).toString('latin1')).toBe('RIFF');
    expect(Buffer.from(downloaded.subarray(8, 12)).toString('latin1')).toBe('WEBP');
    expect(chunkIds(downloaded)).toContain('VP8 ');
    expect(chunkIds(downloaded).filter((id: string) => id === 'EXIF' || id === 'XMP ')).toEqual([]);
    const vp8x = readVp8x(downloaded);
    expect(vp8x.exif).toBe(false);
    expect(vp8x.xmp).toBe(false);
    expect(leakedPrivacyValues(downloaded)).toEqual([]);
    const leakedKeys = await privacyKeysInBytes(downloaded, 'image/webp');
    expect(leakedKeys, `privacy keys still in the downloaded WebP: ${leakedKeys.join(', ')}`).toEqual([]);
    // The source fixture really did carry privacy metadata.
    expect(leakedPrivacyValues(new Uint8Array(webpBytes)).length).toBeGreaterThan(0);
  });

  test('batch: one unverifiable output does not block the other files', async ({ page }) => {
    await page.goto('http://localhost:4321/en');
    await ensureReady(page);

    // JPEG (verifiable) + trailer JPEG (unverifiable) + TIFF (verifiable) +
    // broken WebP (removal throws) in one batch.
    await page.locator('#file-input').setInputFiles([
      cleanJpegPath,
      trailerJpegPath,
      tiffPath,
      malformedWebpPath,
    ]);
    await expect(page.locator('#files-list > div[data-id]')).toHaveCount(4, { timeout: 30000 });
    await expect(page.locator('#remove-1')).toHaveText('Remove metadata', { timeout: 30000 });
    // The auto-strip of the metadata-free trailer file must have settled first
    // (the remove-all button is only shown once busyCount is back to 0).
    await expect(page.locator('#remove-all-btn')).toBeVisible({ timeout: 30000 });

    await page.locator('#remove-all-btn').click();

    // The two verifiable files pass...
    await expect(page.locator('#remove-1')).toHaveText('✓ Success', { timeout: 30000 });
    await expect(page.locator('#remove-3')).toHaveText('✓ Success', { timeout: 30000 });
    await expect(statusOf(page, 1)).toContainText('Privacy metadata remaining: 0');
    await expect(statusOf(page, 3)).toContainText('Privacy metadata remaining: 0');
    await expect(page.locator('#download-1')).toBeEnabled();
    await expect(page.locator('#download-3')).toBeEnabled();

    // ...the unverifiable one is reported, never as a clean zero...
    await expect(statusOf(page, 2)).toContainText('Verification failed', { timeout: 30000 });
    await expect(statusOf(page, 2)).not.toContainText('Privacy metadata remaining: 0');
    await expect(page.locator('#download-2')).toBeDisabled();

    // ...and the broken file keeps the original failure/retry behaviour.
    await expect(page.locator('#remove-4')).toHaveText('Try again', { timeout: 30000 });
    await expect(statusOf(page, 4)).toContainText('Failed to remove metadata');
    await expect(page.locator('#download-4')).toBeDisabled();

    // Nothing is stuck processing and the batch-level state resolved.
    await expect(page.locator('#processing-status')).toHaveClass(/hidden/);

    // The verifiable downloads are really clean.
    const [download] = await Promise.all([
      page.waitForEvent('download'),
      page.locator('#download-1').click(),
    ]);
    const saved = join(workDir, 'batch-clean.jpg');
    await download.saveAs(saved);
    expect(await privacyKeysInBytes(readFileSync(saved), 'image/jpeg')).toEqual([]);
  });

  test('async: a re-upload during removal/verification never contaminates the new batch', async ({ page }) => {
    await page.goto('http://localhost:4321/en');
    await ensureReady(page);

    // Batch A: metadata-bearing files, so removal + verification are in flight.
    await page.locator('#file-input').setInputFiles([cleanJpegPath, trailerJpegPath, tiffPath]);

    // Re-upload immediately (before batch A settles).
    await ensureReady(page);
    await page.locator('#file-input').setInputFiles([]);
    await page.locator('#file-input').setInputFiles(cleanJpegPath);

    // Batch B resolves on its own terms...
    await expect(page.locator('#files-list > div[data-id]')).toHaveCount(1, { timeout: 30000 });
    await expect(statusOf(page, 1)).toContainText('Privacy metadata found', { timeout: 30000 });
    await page.locator('#remove-1').click();
    await expect(page.locator('#remove-1')).toHaveText('✓ Success', { timeout: 30000 });
    await expect(statusOf(page, 1)).toContainText('Privacy metadata remaining: 0');
    await expect(page.locator('#download-1')).toBeEnabled();
    await expect(page.locator('#processing-status')).toHaveClass(/hidden/);

    // ...and is not marked by the discarded batch's verification state.
    await expect(statusOf(page, 1)).not.toContainText('Verification failed');
    await expect(statusOf(page, 1)).not.toContainText('Removing');
  });

  test('responsive: verification result and controls stay usable at all six viewports', async ({ page }) => {
    for (const viewport of VIEWPORTS) {
      await page.setViewportSize({ width: viewport.width, height: viewport.height });
      await page.goto('http://localhost:4321/en');
      await ensureReady(page);

      // Dirty output: the removal runs automatically and its output cannot be
      // verified as clean, so the failure line must render and stay readable.
      await uploadAndAwait(page, trailerJpegPath, 'Verification failed');
      const dirtyStatus = statusOf(page, 1);
      await expect(dirtyStatus).toBeVisible();
      await expect(dirtyStatus).toBeInViewport();
      await expect(dirtyStatus).not.toContainText('Privacy metadata remaining: 0');
      await expect(page.locator('#download-1')).toBeDisabled();
      await page.locator('#remove-1').scrollIntoViewIfNeeded();
      await expect(page.locator('#remove-1')).toBeInViewport();

      let overflow = await page.evaluate(() => ({
        scrollWidth: document.documentElement.scrollWidth,
        clientWidth: document.documentElement.clientWidth,
      }));
      expect(
        overflow.scrollWidth,
        `${viewport.label} (${viewport.width}x${viewport.height}) overflows horizontally on failure`,
      ).toBeLessThanOrEqual(overflow.clientWidth + 1);

      // Verified output: a metadata-free upload is auto-cleaned, verified, and
      // its count + download must stay usable.
      await uploadAndAwait(page, plainJpegPath, 'Metadata removed successfully');
      const verifiedStatus = statusOf(page, 1);
      await expect(verifiedStatus).toContainText('Privacy metadata remaining: 0');
      await expect(verifiedStatus).toBeVisible();
      await expect(page.locator('#remove-1')).toHaveText('✓ Success');
      const downloadBtn = page.locator('#download-1');
      await expect(downloadBtn).toBeEnabled();
      await expect(downloadBtn).toBeInViewport();

      overflow = await page.evaluate(() => ({
        scrollWidth: document.documentElement.scrollWidth,
        clientWidth: document.documentElement.clientWidth,
      }));
      expect(
        overflow.scrollWidth,
        `${viewport.label} (${viewport.width}x${viewport.height}) overflows horizontally when verified`,
      ).toBeLessThanOrEqual(overflow.clientWidth + 1);
    }
  });
});