/**
 * PNG auto-strip decision — regression coverage for the scan → decision gate.
 *
 * What this spec pins down (the actual decision, state and output — not UI
 * copy):
 *
 *   The upload auto-strip in ToolUpload.astro (renderFiles) fires ONLY when
 *   the scan produced a completely empty metadata object — the "nothing
 *   detected at all, proactively hand the user a verified-clean copy" path
 *   taken by metadata-free JPEG/WebP/HEIC files. It is deliberately NOT a
 *   privacy-count gate:
 *
 *   - A clean PNG always yields technical IHDR fields (ImageWidth, BitDepth,
 *     ...) from exifr, so its metadata object is never empty and it must NOT
 *     be auto-stripped. It shows "No privacy metadata found" (privacy count
 *     0) and waits for the user's explicit Remove action — exactly like TIFF,
 *     whose scan also always finds technical fields.
 *   - A corrupt PNG whose scan finds the same technical-only fields must not
 *     be auto-stripped either: it takes the manual path and resolves to a
 *     retryable error instead of flashing a failure on upload.
 *   - A PNG with privacy metadata (eXIf / tEXt / zTXt / iTXt / tIME) reports
 *     a privacy count > 0 and its removal flow is unchanged: manual Remove →
 *     structural strip → output verification → gated download.
 *   - The verified-clean download gate is untouched: the download control
 *     stays disabled until the generated bytes have been re-scanned clean.
 *
 * Run with the dev server up: npx playwright test test-png-autostrip-decision.spec.ts
 */
import { test, expect, type Page } from '@playwright/test';
import { mkdtempSync, writeFileSync, readFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
// @ts-expect-error - plain ESM fixture builder shared with the Node harness
import {
  buildPlainPng, buildRgbExifPng, buildSingleChunkPng, buildMalformedPng,
  readPngChunks, pngChunkTypes, readIhdr, idatBytes, leakedPrivacyValues,
  PNG_PRIVACY_CHUNKS, PNG_SIGNATURE,
} from './test-png-fixture.mjs';

const VIEWPORTS = [
  { width: 375, height: 667, label: 'mobile-small' },
  { width: 390, height: 844, label: 'mobile-large' },
  { width: 768, height: 1024, label: 'tablet' },
  { width: 820, height: 1180, label: 'tablet-large' },
  { width: 1280, height: 800, label: 'laptop' },
  { width: 1440, height: 900, label: 'desktop' },
];

const SIZE = { width: 120, height: 80 };

let workDir = '';
let plainPath = '';
let exifPath = '';
let malformedPath = '';
let textOnlyPaths: Record<string, string> = {};

test.beforeAll(async () => {
  workDir = mkdtempSync(join(tmpdir(), 'pmr-png-autostrip-'));
  writeFileSync((plainPath = join(workDir, 'clean-plain.png')), await buildPlainPng(SIZE));
  writeFileSync((exifPath = join(workDir, 'with-exif.png')), await buildRgbExifPng(SIZE));
  writeFileSync((malformedPath = join(workDir, 'broken.png')), buildMalformedPng());
  textOnlyPaths = {};
  for (const chunkType of ['tEXt', 'zTXt', 'iTXt', 'tIME']) {
    const path = join(workDir, `only-${chunkType}.png`);
    writeFileSync(path, await buildSingleChunkPng(chunkType, SIZE));
    textOnlyPaths[chunkType] = path;
  }
});

test.afterAll(() => {
  if (workDir) {
    try {
      rmSync(workDir, { recursive: true, force: true });
    } catch {
      /* ignore */
    }
  }
});

async function ensureReady(page: Page): Promise<void> {
  await page.waitForLoadState('networkidle');
  await page.waitForSelector('body[data-pmr-ready]', { timeout: 10000 });
}

async function uploadOne(page: Page, filePath: string): Promise<void> {
  await page.goto('http://localhost:4321/en');
  await ensureReady(page);
  await page.locator('#file-input').setInputFiles(filePath);
  await expect(page.locator('#files-list > div[data-id]')).toHaveCount(1, { timeout: 30000 });
}

/**
 * Assert the auto-strip decision did NOT fire for the uploaded item. The
 * decision runs with the render that publishes the scan status, so once the
 * terminal scan state is visible the label/download state already reflects
 * it; the short settle then proves nothing flips afterwards either.
 */
async function expectNotAutoStripped(page: Page): Promise<void> {
  const removeBtn = page.locator('#remove-1');
  const downloadBtn = page.locator('#download-1');
  await expect(removeBtn).toHaveText('Remove metadata');
  await expect(removeBtn).toBeEnabled();
  await expect(downloadBtn).toBeDisabled();
  await page.waitForTimeout(750);
  await expect(removeBtn).toHaveText('Remove metadata');
  await expect(removeBtn).toBeEnabled();
  await expect(downloadBtn).toBeDisabled();
}

/** Open the per-file viewer and return its rows with their privacy highlight. */
async function openPanelRows(page: Page): Promise<Array<{ label: string; value: string; privacy: boolean }>> {
  await page.locator('#meta-toggle-1').click();
  await expect(page.locator('#metadata-panel-1')).toBeVisible({ timeout: 5000 });
  return page.$$eval('#metadata-panel-1 > div > div', (rows) =>
    rows.map((row) => ({
      label: (row.children[0] as HTMLElement | undefined)?.textContent?.trim() ?? '',
      value: (row.children[1] as HTMLElement | undefined)?.textContent?.trim() ?? '',
      privacy: row.className.includes('bg-warning-bg'),
    })),
  );
}

/**
 * Byte-level assertions on a downloaded clean PNG, made with the fixture
 * module's independent chunk walker (never with the application code).
 */
function expectCleanPngBytes(saved: string, source: string): void {
  const bytes = readFileSync(saved);
  expect(bytes.subarray(0, 8).equals(PNG_SIGNATURE), 'download is not a PNG').toBe(true);

  const chunks = readPngChunks(bytes); // throws on any structural/CRC defect
  expect(chunks[0].type).toBe('IHDR');
  expect(chunks[chunks.length - 1].type).toBe('IEND');

  const types = pngChunkTypes(bytes);
  for (const type of PNG_PRIVACY_CHUNKS) {
    expect(types.filter((t: string) => t === type), `${type} chunk still present`).toEqual([]);
  }
  expect(leakedPrivacyValues(bytes), 'privacy payload bytes still present').toEqual([]);

  const inIhdr = readIhdr(readFileSync(source));
  const outIhdr = readIhdr(bytes);
  expect(outIhdr.width).toBe(inIhdr.width);
  expect(outIhdr.height).toBe(inIhdr.height);
  expect(outIhdr.bitDepth).toBe(inIhdr.bitDepth);
  expect(outIhdr.colorType).toBe(inIhdr.colorType);
  expect(idatBytes(bytes).equals(idatBytes(readFileSync(source))), 'IDAT was re-encoded').toBe(true);
}

/** Drive the manual removal flow to its verified end state and download. */
async function removeVerifyDownload(page: Page, savedName: string): Promise<string> {
  await page.locator('#remove-1').click();
  await expect(page.locator('#remove-1')).toHaveText('✓ Success', { timeout: 30000 });
  const status = page.locator('[data-id="1"] .text-xs');
  await expect(status).toContainText('Metadata removed successfully');
  await expect(status).toContainText('Privacy metadata remaining: 0');
  await expect(page.locator('#download-1')).toBeEnabled();

  const [download] = await Promise.all([page.waitForEvent('download'), page.locator('#download-1').click()]);
  const saved = join(workDir, savedName);
  await download.saveAs(saved);
  return saved;
}

test.describe('PNG auto-strip decision', () => {
  test('clean PNG (IHDR only): privacy count 0, NOT auto-stripped, manual removal ends verified clean', async ({ page }) => {
    await uploadOne(page, plainPath);

    // Scan result: no privacy metadata, only technical PNG structure.
    const status = page.locator('[data-id="1"] .text-xs');
    await expect(status).toContainText('No privacy metadata found', { timeout: 30000 });
    await expect(status).toContainText('Technical image information preserved');
    await expect(page.locator('#meta-toggle-1')).toContainText('technical info');

    // The decision: technical PNG fields alone must never trigger auto-strip.
    await expectNotAutoStripped(page);

    // Privacy classification of the real scan output: zero flagged rows, and
    // the IHDR-derived technical rows are present but unflagged.
    const rows = await openPanelRows(page);
    expect(rows.length, 'expected the technical IHDR fields in the viewer').toBeGreaterThan(0);
    expect(rows.filter((row) => row.privacy), 'technical PNG fields flagged as privacy').toEqual([]);
    expect(rows.some((row) => row.label === 'ImageWidth')).toBe(true);

    // The manual removal flow still produces a verified, byte-clean download.
    const saved = await removeVerifyDownload(page, 'clean-plain-download.png');
    expectCleanPngBytes(saved, plainPath);
  });

  test('PNG with eXIf: privacy count > 0, NOT auto-stripped, removal flow verifies and downloads', async ({ page }) => {
    await uploadOne(page, exifPath);

    // The eXIf block contributes Make/Model/Software/Copyright (4 fields).
    const status = page.locator('[data-id="1"] .text-xs');
    await expect(status).toContainText('Privacy metadata found (4)', { timeout: 30000 });

    // Files with detected metadata wait for the explicit Remove action.
    await expectNotAutoStripped(page);

    const saved = await removeVerifyDownload(page, 'clean-exif-download.png');
    expectCleanPngBytes(saved, exifPath);
    expect(pngChunkTypes(readFileSync(saved))).not.toContain('eXIf');
  });

  test('PNG with tEXt privacy chunk: privacy count 1, removal flow verifies and downloads', async ({ page }) => {
    await uploadOne(page, textOnlyPaths['tEXt']);

    const status = page.locator('[data-id="1"] .text-xs');
    await expect(status).toContainText('Privacy metadata found (1)', { timeout: 30000 });

    await expectNotAutoStripped(page);

    const saved = await removeVerifyDownload(page, 'clean-text-download.png');
    expectCleanPngBytes(saved, textOnlyPaths['tEXt']);
    expect(pngChunkTypes(readFileSync(saved))).not.toContain('tEXt');
  });

  for (const chunkType of ['zTXt', 'iTXt', 'tIME']) {
    test(`PNG with only ${chunkType}: privacy count 1, removal flow verifies and downloads`, async ({ page }) => {
      const source = textOnlyPaths[chunkType];
      await uploadOne(page, source);

      const status = page.locator('[data-id="1"] .text-xs');
      await expect(status).toContainText('Privacy metadata found (1)', { timeout: 30000 });

      await expectNotAutoStripped(page);

      const saved = await removeVerifyDownload(page, `clean-only-${chunkType}-download.png`);
      expectCleanPngBytes(saved, source);
      expect(pngChunkTypes(readFileSync(saved)), `${chunkType} survived removal`).not.toContain(chunkType);
    });
  }

  test('malformed PNG (technical-only scan): NOT auto-stripped, manual path resolves to a retryable error', async ({ page }) => {
    await uploadOne(page, malformedPath);

    // The corrupt container scans as technical-only (its IHDR parses): it must
    // never be auto-stripped, because the strip would fail on upload without
    // the user asking for anything.
    const status = page.locator('[data-id="1"] .text-xs');
    await expect(status).toContainText('No privacy metadata found', { timeout: 30000 });
    await expectNotAutoStripped(page);

    // The manual path fails loudly and resolves instead of hanging.
    await page.locator('#remove-1').click();
    await expect(page.locator('#remove-1')).toHaveText('Try again', { timeout: 30000 });
    await expect(status).toContainText('Failed to remove metadata');
    await expect(page.locator('#download-1')).toBeDisabled();
    await expect(page.locator('#processing-status')).toHaveClass(/hidden/);
  });

  test('verified-clean gate: the download stays disabled until the generated output is re-scanned', async ({ page }) => {
    // Keep the removal/verification window observable: delay the first read of
    // the generated output bytes (mirrors the helper in test-png-removal.spec.ts).
    await page.addInitScript(() => {
      const w = window as unknown as { __pmrDelayUsed?: boolean };
      w.__pmrDelayUsed = false;
      const original = Blob.prototype.arrayBuffer;
      Blob.prototype.arrayBuffer = function (this: Blob): Promise<ArrayBuffer> {
        return original.call(this).then(async (buf: ArrayBuffer) => {
          if (this instanceof File || w.__pmrDelayUsed) return buf;
          w.__pmrDelayUsed = true;
          await new Promise((resolve) => setTimeout(resolve, 1200));
          return buf;
        });
      };
    });

    await uploadOne(page, exifPath);
    await expectNotAutoStripped(page);

    await page.locator('#remove-1').click();
    // Processing state is usable and the gate holds while the output is made
    // and re-scanned.
    await expect(page.locator('[data-id="1"] .text-xs')).toHaveText(/Removing|Verifying/, { timeout: 30000 });
    await expect(page.locator('#download-1')).toBeDisabled();

    // 60s handles dev-server contention when the full suite runs in parallel
    // (same headroom the launch-gate spec allows for cold starts).
    await expect(page.locator('#remove-1')).toHaveText('✓ Success', { timeout: 60000 });
    await expect(page.locator('[data-id="1"] .text-xs')).toContainText('Privacy metadata remaining: 0');
    await expect(page.locator('#download-1')).toBeEnabled();
  });

  test('responsive: clean-PNG decision state stays correct at all six viewports', async ({ page }) => {
    for (const viewport of VIEWPORTS) {
      await page.setViewportSize({ width: viewport.width, height: viewport.height });
      await uploadOne(page, plainPath);

      // Scan result and privacy classification remain visible.
      const status = page.locator('[data-id="1"] .text-xs');
      await expect(status).toContainText('No privacy metadata found', { timeout: 30000 });
      await expect(status).toContainText('Technical image information preserved');

      // Upload area remains usable.
      const uploadZone = await page.locator('#upload-zone').boundingBox();
      expect(uploadZone, `${viewport.label}: upload zone not rendered`).not.toBeNull();
      expect(uploadZone!.width).toBeGreaterThan(0);

      // Decision: never auto-stripped; Remove usable, download gated.
      const removeBtn = page.locator('#remove-1');
      await expect(removeBtn).toHaveText('Remove metadata');
      await expect(removeBtn).toBeEnabled();
      await expect(page.locator('#download-1')).toBeDisabled();

      // No horizontal page overflow.
      const overflow = await page.evaluate(() => ({
        scrollWidth: document.documentElement.scrollWidth,
        clientWidth: document.documentElement.clientWidth,
      }));
      expect(
        overflow.scrollWidth,
        `${viewport.label} (${viewport.width}x${viewport.height}) overflows horizontally`,
      ).toBeLessThanOrEqual(overflow.clientWidth + 1);
    }
  });

  test('responsive: privacy-PNG flow stays usable at all six viewports', async ({ page }) => {
    for (const viewport of VIEWPORTS) {
      await page.setViewportSize({ width: viewport.width, height: viewport.height });
      await uploadOne(page, exifPath);

      // Scan result and the privacy count remain visible.
      const status = page.locator('[data-id="1"] .text-xs');
      await expect(status).toContainText('Privacy metadata found (4)', { timeout: 30000 });

      // Decision: waits for the explicit Remove action at every viewport.
      const removeBtn = page.locator('#remove-1');
      await expect(removeBtn).toHaveText('Remove metadata');
      await expect(removeBtn).toBeEnabled();
      await expect(page.locator('#download-1')).toBeDisabled();

      // Processing state remains usable and the download gate holds until the
      // generated output is verified.
      await removeBtn.click();
      await expect(page.locator('#remove-1')).toHaveText('✓ Success', { timeout: 30000 });
      const downloadBtn = page.locator('#download-1');
      await expect(downloadBtn).toBeEnabled();
      await expect(downloadBtn).toBeInViewport();

      // No horizontal page overflow.
      const overflow = await page.evaluate(() => ({
        scrollWidth: document.documentElement.scrollWidth,
        clientWidth: document.documentElement.clientWidth,
      }));
      expect(
        overflow.scrollWidth,
        `${viewport.label} (${viewport.width}x${viewport.height}) overflows horizontally`,
      ).toBeLessThanOrEqual(overflow.clientWidth + 1);
    }
  });
});
