/**
 * ZIP verification gating - permanent regression spec.
 *
 * The integrity gap this pins down:
 *   `#download-all-btn` was un-hidden/usable as soon as ANY item had a
 *   `cleanBlob`, but `cleanBlob` is published BEFORE verification runs. So the
 *   batch ZIP could be built - and downloaded - while an entry was still
 *   `verifyStatus === 'verifying'`, shipping bytes that the app's own verifier
 *   then rejected. A second defect compounded it: the button carries both
 *   `hidden` and `inline-flex`, and `inline-flex` wins in the compiled Tailwind
 *   output, so `classList.toggle('hidden', ...)` never actually hid it - and the
 *   button was never `disabled` either.
 *
 * What is proven here (all against the real generated bytes):
 *   1  no verified output yet            -> ZIP disabled, no download
 *   2  1 verified + 1 verifying          -> ZIP disabled, no download
 *   3  Remove All + held verification    -> ZIP disabled, no download
 *   4  out-of-order verification         -> ZIP disabled until all settle
 *   5  verification failure              -> failed output never enters the ZIP
 *   6  single-item fallback              -> both download paths refuse
 *   7  stale batch                       -> old batch never affects the new one
 *   8  actual ZIP content                -> only passed items, no privacy values
 *   9  all six viewports                 -> real, observable disabled state
 *
 * Verification is NEVER faked: the only instrumentation delays the RESOLUTION of
 * the generated-output byte read (`Blob.prototype.arrayBuffer` for non-File
 * blobs), so the app still reads, re-parses and re-classifies the same bytes.
 * It only widens the 'verifying' window so that window is observable.
 *
 * Run with the dev server up: npx playwright test zip-verification-gating.spec.ts
 */
import { test, expect, type Page } from '@playwright/test';
import { mkdtempSync, writeFileSync, readFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
// @ts-expect-error - plain ESM fixture builders shared with the Node harness
import {
  buildVerifiedCleanJpeg,
  buildTrailerExifJpeg,
  buildPlainJpeg,
  PRIVACY_VALUES,
  containsLatin1,
  privacyKeysInBytes,
} from './test-output-verification-fixture.mjs';

const BASE = 'http://localhost:4321/en';
const ZIP_BTN = '#download-all-btn';

const VIEWPORTS = [
  { width: 375, height: 667, label: 'mobile-small' },
  { width: 390, height: 844, label: 'mobile-large' },
  { width: 768, height: 1024, label: 'tablet' },
  { width: 820, height: 1180, label: 'tablet-large' },
  { width: 1280, height: 800, label: 'laptop' },
  { width: 1440, height: 900, label: 'desktop' },
];

let workDir = '';
let cleanJpegPath = ''; // metadata-bearing -> manual removal -> verifies clean
let cleanJpegPath2 = ''; // same bytes, distinct file/name
let cleanJpegPath3 = ''; // same bytes, distinct file/name
let trailerJpegPath = ''; // EXIF after EOI -> auto-strip -> verification FAILS
let plainJpegPath = ''; // metadata-free -> auto-strip -> verification passes
let cleanJpegBytes: Buffer = Buffer.alloc(0);
let trailerBytes: Buffer = Buffer.alloc(0);

/** The privacy payload carried by the trailer fixture. */
const NEEDLE = PRIVACY_VALUES[3]; // 'Jane Photographer'

// ------------------------------------------------------------------- helpers

async function ensureReady(page: Page): Promise<void> {
  await page.waitForLoadState('networkidle');
  await page.waitForSelector('body[data-pmr-ready]', { timeout: 10000 });
}

/** The per-file status element that carries the verification result. */
function statusOf(page: Page, id: number) {
  return page.locator(`[data-id="${id}"] .text-xs`).first();
}

/** Everything that decides whether the ZIP control is usable. */
async function probe(page: Page, selector: string) {
  return page.evaluate((sel) => {
    const el = document.querySelector(sel) as HTMLButtonElement | null;
    if (!el) return null;
    const cs = getComputedStyle(el);
    const rect = el.getBoundingClientRect();
    const panel = document.getElementById('results-panel');
    // A disabled button is not focusable, so this also proves the keyboard
    // cannot reach the control.
    el.focus();
    return {
      disabled: el.disabled,
      matchesDisabled: el.matches(':disabled'),
      ariaDisabled: el.getAttribute('aria-disabled'),
      hasHiddenClass: el.classList.contains('hidden'),
      display: cs.display,
      visibility: cs.visibility,
      rect: { w: Math.round(rect.width), h: Math.round(rect.height) },
      focusable: document.activeElement === el,
      panelHidden: panel ? panel.classList.contains('hidden') : null,
    };
  }, selector);
}

/**
 * Delay the RESOLUTION of the generated-output byte read inside the 'verifying'
 * window. Two independent triggers:
 *   __pmrDelayNeedle + __pmrDelayMs : first non-File read whose latin1 bytes
 *                                     contain the needle (one dirty output)
 *   __pmrDelayFirstCleanMs          : first non-File read at all
 * One-shot per page, so ZIP generation reads are never delayed.
 */
async function installDelayHook(page: Page): Promise<void> {
  await page.addInitScript(() => {
    const w = window as unknown as Record<string, unknown>;
    w.__pmrDelayMs = 0;
    w.__pmrDelayNeedle = '';
    w.__pmrDelayFirstCleanMs = 0;
    w.__pmrDelayUsed = false;
    w.__pmrDelayTrail = [];

    const original = Blob.prototype.arrayBuffer;
    Blob.prototype.arrayBuffer = function (this: Blob) {
      const meta = this as unknown as { size: number; type: string };
      return original.call(this).then(async (buf: ArrayBuffer) => {
        if (this instanceof File) return buf; // upload / strip reads
        if (w.__pmrDelayUsed) return buf;
        const bytes = new Uint8Array(buf);
        let latin = '';
        for (let i = 0; i < bytes.length; i++) latin += String.fromCharCode(bytes[i]);

        let ms = 0;
        let trigger = '';
        const needle = String(w.__pmrDelayNeedle || '');
        if (needle && latin.includes(needle)) {
          ms = Number(w.__pmrDelayMs) || 0;
          trigger = 'needle:' + needle;
        } else if (!needle && Number(w.__pmrDelayFirstCleanMs) > 0) {
          ms = Number(w.__pmrDelayFirstCleanMs);
          trigger = 'first-clean-read';
        }

        (w.__pmrDelayTrail as string[]).push(
          'read type=' + meta.type + ' size=' + meta.size + ' trigger=' + (trigger || 'none') + ' ms=' + ms,
        );
        if (ms > 0) {
          w.__pmrDelayUsed = true;
          await new Promise((r) => setTimeout(r, ms));
        }
        return buf;
      });
    };
  });
}

async function setDelay(page: Page, opts: { needle?: string; ms?: number; firstCleanMs?: number }) {
  await page.evaluate((o) => {
    const w = window as unknown as Record<string, unknown>;
    w.__pmrDelayNeedle = o.needle || '';
    w.__pmrDelayMs = o.ms || 0;
    w.__pmrDelayFirstCleanMs = o.firstCleanMs || 0;
    w.__pmrDelayUsed = false;
    w.__pmrDelayTrail = [];
  }, opts);
}

async function delayTrail(page: Page): Promise<string[]> {
  return page.evaluate(() => (window as unknown as { __pmrDelayTrail: string[] }).__pmrDelayTrail);
}

/** Real user click, tolerating a disabled (non-actionable) button. */
async function attemptRealClick(page: Page, selector: string): Promise<void> {
  await page
    .locator(selector)
    .click({ force: true, timeout: 3000 })
    .catch(() => undefined);
}

/**
 * Dispatch a synthetic click straight at the element, so the app's own handler
 * runs even while the button is `disabled`. This bypasses the UI gate on purpose
 * to prove the in-code defence-in-depth layer refuses unverified output.
 */
async function syntheticActivate(page: Page, selector: string): Promise<void> {
  await page.evaluate((sel) => {
    const el = document.querySelector(sel) as HTMLElement | null;
    el?.dispatchEvent(new MouseEvent('click', { bubbles: true, cancelable: true, composed: true }));
  }, selector);
}

/** Assert that `action` produces no download at all. */
async function expectNoDownload(page: Page, action: () => Promise<void>, ms = 2500): Promise<void> {
  let downloaded = false;
  const waiter = page
    .waitForEvent('download', { timeout: ms })
    .then(() => {
      downloaded = true;
    })
    .catch(() => undefined);
  await action();
  await waiter;
  expect(downloaded, 'no download must be produced').toBe(false);
}

/**
 * Forced (synthetic) activation deliberately bypasses `disabled`, so the in-code
 * gate is what is under test. Whatever the handler ships must consist of
 * VERIFIED-clean outputs only: the still-verifying entry must never be included,
 * and no privacy fixture value may appear in any shipped byte.
 *
 * Shipping nothing at all is also a correct outcome - that is what happens while
 * no verified output exists yet.
 */
async function expectForcedActivationShipsNoUnverified(page: Page, label: string): Promise<void> {
  const waiter = page.waitForEvent('download', { timeout: 5000 }).catch(() => null);
  await syntheticActivate(page, ZIP_BTN);
  const dl = await waiter;
  if (!dl) return;

  const name = dl.suggestedFilename();
  expect(name, `${label}: the still-verifying entry must never be shipped`).not.toContain('trailer');

  const saved = join(workDir, `${label.replace(/[^a-zA-Z0-9]+/g, '_')}-forced`);
  await dl.saveAs(saved);
  const bytes = readFileSync(saved);

  if (name.toLowerCase().endsWith('.zip')) {
    const JSZip = (await import('jszip')).default;
    const zip = await JSZip.loadAsync(bytes);
    for (const entryName of Object.keys(zip.files)) {
      expect(
        entryName,
        `${label}: the still-verifying entry must never be shipped`,
      ).not.toContain('trailer');
      const entryBytes = Buffer.from(await zip.files[entryName].async('uint8array'));
      expect(
        PRIVACY_VALUES.filter((v) => containsLatin1(entryBytes, v)),
        `${label}: a forced ZIP must carry no privacy values`,
      ).toEqual([]);
    }
    return;
  }

  expect(
    PRIVACY_VALUES.filter((v) => containsLatin1(bytes, v)),
    `${label}: a forced download must carry no privacy values`,
  ).toEqual([]);
}

/** The ZIP button must be genuinely unavailable (disabled + aria + not focusable). */
async function expectZipUnavailable(page: Page, label: string): Promise<void> {
  const p = await probe(page, ZIP_BTN);
  expect(p, `${label}: ZIP button must exist`).not.toBeNull();
  expect(p!.disabled, `${label}: ZIP button must be disabled`).toBe(true);
  expect(p!.matchesDisabled, `${label}: :disabled must match (UA blocks activation)`).toBe(true);
  expect(p!.ariaDisabled, `${label}: aria-disabled must mirror disabled`).toBe('true');
  expect(p!.focusable, `${label}: a disabled ZIP button must not be keyboard focusable`).toBe(false);
}

/** The ZIP button must be genuinely usable. */
async function expectZipAvailable(page: Page, label: string): Promise<void> {
  const p = await probe(page, ZIP_BTN);
  expect(p!.disabled, `${label}: ZIP button must be enabled`).toBe(false);
  expect(p!.ariaDisabled, `${label}: aria-disabled must mirror disabled`).toBe('false');
  expect(p!.visibility, `${label}: ZIP button must be visible`).toBe('visible');
  expect(p!.panelHidden, `${label}: results panel must be visible`).toBe(false);
}

test.beforeAll(async () => {
  workDir = mkdtempSync(join(tmpdir(), 'pmr-zipgate-'));
  cleanJpegBytes = await buildVerifiedCleanJpeg();
  writeFileSync((cleanJpegPath = join(workDir, 'gate-one.jpg')), cleanJpegBytes);
  writeFileSync((cleanJpegPath2 = join(workDir, 'gate-two.jpg')), cleanJpegBytes);
  writeFileSync((cleanJpegPath3 = join(workDir, 'gate-three.jpg')), cleanJpegBytes);
  const trailer = await buildTrailerExifJpeg();
  trailerBytes = trailer.bytes;
  writeFileSync((trailerJpegPath = join(workDir, 'gate-trailer.jpg')), trailerBytes);
  writeFileSync((plainJpegPath = join(workDir, 'gate-plain.jpg')), await buildPlainJpeg());

  // The trailer fixture really does carry the privacy payload the ZIP must never
  // ship, and its output is byte-identical to the source (EXIF sits after EOI).
  expect(containsLatin1(trailerBytes, NEEDLE)).toBe(true);
});

test.afterAll(() => {
  if (workDir) rmSync(workDir, { recursive: true, force: true });
});

// ===========================================================================
// TEST 1 - zero verified-clean output: the ZIP control must be unavailable.
// ===========================================================================
test('TEST 1 - no verified output yet: ZIP disabled, aria-disabled set, click produces nothing', async ({
  page,
}) => {
  await page.goto(BASE);
  await ensureReady(page);

  // Metadata-bearing upload: nothing is auto-stripped, so no output exists yet.
  await page.locator('#file-input').setInputFiles([cleanJpegPath, cleanJpegPath2]);
  await expect(page.locator('#files-list > div[data-id]')).toHaveCount(2, { timeout: 30000 });
  await expect(statusOf(page, 1)).toContainText('Privacy metadata found', { timeout: 30000 });

  await expectZipUnavailable(page, 'TEST 1 (nothing clean)');
  await expect(page.locator(ZIP_BTN)).toBeDisabled();

  // A real click (forced past actionability) must not start anything.
  await expectNoDownload(page, () => attemptRealClick(page, ZIP_BTN));
  // Even the synthetic activation that reaches the handler must refuse.
  await expectNoDownload(page, () => syntheticActivate(page, ZIP_BTN));
  console.log('TEST 1 PASSED: ZIP unavailable with zero verified output');
});

// ===========================================================================
// TEST 2 - 1 verified + 1 verifying: ZIP must stay disabled until it settles.
// ===========================================================================
test('TEST 2 - 1 verified + 1 verifying: ZIP stays disabled and downloads nothing', async ({ page }) => {
  test.setTimeout(120000);
  await installDelayHook(page);
  await page.goto(BASE);
  await ensureReady(page);
  // Hold ONLY the trailer's output in the 'verifying' window (dirty bytes).
  await setDelay(page, { needle: NEEDLE, ms: 12000 });

  // item 1 = trailer -> auto-strip starts immediately (verification held)
  // item 2 = clean   -> manual removal, verifies normally
  await page.locator('#file-input').setInputFiles([trailerJpegPath, cleanJpegPath]);
  await expect(page.locator('#files-list > div[data-id]')).toHaveCount(2, { timeout: 30000 });
  await expect(statusOf(page, 1)).toContainText('Verifying clean output', { timeout: 30000 });

  await expect(page.locator('#remove-2')).toHaveText('Remove metadata', { timeout: 30000 });
  await page.locator('#remove-2').click();
  await expect(page.locator('#remove-2')).toHaveText(/Success/, { timeout: 30000 });
  await expect(page.locator('#download-2')).toBeEnabled();

  // 1 verified-clean + 1 verifying => ZIP must NOT be usable.
  expect((await statusOf(page, 1).textContent()) || '', 'item 1 is still verifying').toContain(
    'Verifying clean output',
  );
  await expectZipUnavailable(page, 'TEST 2 (1 verified + 1 verifying)');
  // Real UI click: the disabled control starts nothing at all.
  await expectNoDownload(page, () => attemptRealClick(page, ZIP_BTN));
  // Forced activation bypasses `disabled`, so the in-code gate is what must
  // refuse the still-verifying entry (only verified items may ever ship).
  await expectForcedActivationShipsNoUnverified(page, 'TEST 2');

  // Any forced path must never ship the still-verifying (dirty) entry: it was
  // rejected by the app's own verifier, so it can never be "passed".
  await expect(statusOf(page, 1)).toContainText('Verification failed', { timeout: 90000 });

  // Once every item has settled, the control opens again and - because only one
  // verified entry remains - the single-item path delivers exactly that file.
  // (This also acts as the positive control proving synthetic activation really
  // does reach the app's handler, so the negative assertions above are real.)
  await expectZipAvailable(page, 'TEST 2 (after verification settled)');
  const downloadPromise = page.waitForEvent('download', { timeout: 60000 });
  await syntheticActivate(page, ZIP_BTN);
  const settledDownload = await downloadPromise;
  expect(settledDownload.suggestedFilename(), 'only the verified entry is delivered').toBe(
    'gate-one-clean.jpg',
  );
  const settledSaved = join(workDir, 'test2-settled.jpg');
  await settledDownload.saveAs(settledSaved);
  const settledBytes = readFileSync(settledSaved);
  expect(PRIVACY_VALUES.filter((v) => containsLatin1(settledBytes, v))).toEqual([]);
  expect(await privacyKeysInBytes(settledBytes, 'image/jpeg')).toEqual([]);

  console.log('TEST 2 PASSED: ZIP stayed disabled; no download while verifying');
  console.log('[TEST 2] delay trail:', JSON.stringify(await delayTrail(page)));
});

// ===========================================================================
// TEST 3 - Remove All: ZIP must stay disabled while verification is running.
// ===========================================================================
test('TEST 3 - Remove All with held verification: ZIP disabled, no download', async ({ page }) => {
  test.setTimeout(120000);
  await installDelayHook(page);
  await page.goto(BASE);
  await ensureReady(page);
  await setDelay(page, { firstCleanMs: 12000 });

  await page.locator('#file-input').setInputFiles([cleanJpegPath, cleanJpegPath2]);
  await expect(page.locator('#files-list > div[data-id]')).toHaveCount(2, { timeout: 30000 });
  await expect(statusOf(page, 1)).toContainText('Privacy metadata found', { timeout: 30000 });

  await page.locator('#remove-all-btn').click();
  await expect(statusOf(page, 1)).toContainText('Verifying clean output', { timeout: 30000 });

  // Item 1 holds a cleanBlob but is NOT verified yet -> ZIP must be unavailable.
  await expectZipUnavailable(page, 'TEST 3 (remove-all verifying)');
  await expectNoDownload(page, () => attemptRealClick(page, ZIP_BTN));
  await expectNoDownload(page, () => syntheticActivate(page, ZIP_BTN));

  // Both files settle as verified -> the control opens.
  await expect(page.locator('#remove-2')).toHaveText(/Success/, { timeout: 90000 });
  await expect(statusOf(page, 1)).toContainText('Metadata removed successfully', { timeout: 90000 });
  await expectZipAvailable(page, 'TEST 3 (after remove-all settled)');
  console.log('TEST 3 PASSED: Remove All kept ZIP disabled until verification settled');
});

// ===========================================================================
// TEST 4 - out-of-order verification: ZIP stays disabled until everything settles.
// ===========================================================================
test('TEST 4 - out-of-order verification: ZIP disabled until all settle, then enabled', async ({
  page,
}) => {
  test.setTimeout(120000);
  await installDelayHook(page);
  await page.goto(BASE);
  await ensureReady(page);
  await setDelay(page, { needle: NEEDLE, ms: 12000 });

  // item 1 trailer -> auto-strip, verification held (dirty)
  // item 2 plain   -> auto-strip, verifies immediately
  // item 3 clean   -> verifies on demand
  await page.locator('#file-input').setInputFiles([trailerJpegPath, plainJpegPath, cleanJpegPath]);
  await expect(page.locator('#files-list > div[data-id]')).toHaveCount(3, { timeout: 30000 });

  await expect(statusOf(page, 2)).toContainText('Metadata removed successfully', { timeout: 60000 });
  await expect(statusOf(page, 1)).toContainText('Verifying clean output', { timeout: 30000 });
  await page.locator('#remove-3').click();
  await expect(page.locator('#remove-3')).toHaveText(/Success/, { timeout: 60000 });

  // 2 passed + 1 still verifying => ZIP must remain disabled.
  await expectZipUnavailable(page, 'TEST 4 (2 passed + 1 verifying)');
  // Real UI click: the disabled control starts nothing at all.
  await expectNoDownload(page, () => attemptRealClick(page, ZIP_BTN));
  // Forced activation bypasses `disabled`: the handler may only ship verified
  // outputs, and must never include the held (dirty) entry.
  await expectForcedActivationShipsNoUnverified(page, 'TEST 4');

  // Once the held verification settles (here: rejected), the control opens for
  // the entries that really passed.
  await expect(statusOf(page, 1)).toContainText('Verification failed', { timeout: 90000 });
  await expectZipAvailable(page, 'TEST 4 (after settle)');
    console.log('TEST 4 PASSED: ZIP disabled until all verification settled');
});

// ===========================================================================
// TEST 5 - verification failure: failed output must NOT enter the ZIP.
// ===========================================================================
test('TEST 5 - verification failure keeps failed output out of the ZIP', async ({
  page,
}) => {
  test.setTimeout(120000);
  await installDelayHook(page);
  await page.goto(BASE);
  await ensureReady(page);
  await setDelay(page, { needle: NEEDLE, ms: 10000 });

  // item 1 = trailer -> auto-strip, verification held, will FAIL
  // item 2 = clean   -> manual removal, verifies clean
  // item 3 = clean   -> manual removal, verifies clean
  // Two verified items remain, so the real multi-entry ZIP path is exercised.
  await page.locator('#file-input').setInputFiles([trailerJpegPath, cleanJpegPath, cleanJpegPath2]);
  await expect(page.locator('#files-list > div[data-id]')).toHaveCount(3, { timeout: 30000 });
  await expect(statusOf(page, 1)).toContainText('Verifying clean output', { timeout: 30000 });

  await page.locator('#remove-2').click();
  await expect(page.locator('#remove-2')).toHaveText(/Success/, { timeout: 60000 });
  await expect(page.locator('#download-2')).toBeEnabled();
  await page.locator('#remove-3').click();
  await expect(page.locator('#remove-3')).toHaveText(/Success/, { timeout: 60000 });
  await expect(page.locator('#download-3')).toBeEnabled();

  // 2 verified + 1 still verifying => ZIP must stay unavailable.
  await expectZipUnavailable(page, 'TEST 5 (2 passed + 1 failing)');
  await expectNoDownload(page, () => attemptRealClick(page, ZIP_BTN));

  await expect(statusOf(page, 1)).toContainText('Verification failed', { timeout: 90000 });
  await expectZipAvailable(page, 'TEST 5 (failed settled, 2 verified remain)');

  const downloadPromise = page.waitForEvent('download', { timeout: 60000 });
  await syntheticActivate(page, ZIP_BTN);
  const zipDownload = await downloadPromise;
  const zipPath = join(workDir, 'test5-failed.zip');
  await zipDownload.saveAs(zipPath);
  const zipBytes = readFileSync(zipPath);

  const JSZip = (await import('jszip')).default;
  const zip = await JSZip.loadAsync(zipBytes);
  const names = Object.keys(zip.files);
  expect(names, 'ZIP must contain exactly the verified items').toHaveLength(2);
  expect(names.join(' '), 'the failed output must never enter the ZIP').not.toContain('trailer');
  expect(names.join(' ')).toContain('gate-one');
  expect(names.join(' ')).toContain('gate-two');

  for (const name of names) {
    const entryBytes = await zip.files[name].async('uint8array');
    expect(PRIVACY_VALUES.filter((v) => containsLatin1(Buffer.from(entryBytes), v))).toEqual([]);
    expect(await privacyKeysInBytes(Buffer.from(entryBytes), 'image/jpeg')).toEqual([]);
  }

  console.log('TEST 5 PASSED: failed output excluded from ZIP; only verified items shipped');
  console.log('[TEST 5] zip entries:', JSON.stringify(names));
});

// ===========================================================================
// TEST 6 - single-item fallback: downloadItem() must refuse unverified.
// ===========================================================================
test('TEST 6 - single-item fallback refuses unverified blob', async ({ page }) => {
  test.setTimeout(120000);
  await installDelayHook(page);
  await page.goto(BASE);
  await ensureReady(page);
  await setDelay(page, { firstCleanMs: 10000 });

  await page.locator('#file-input').setInputFiles([cleanJpegPath]);
  await expect(page.locator('#files-list > div[data-id]')).toHaveCount(1, { timeout: 30000 });
  await expect(statusOf(page, 1)).toContainText('Privacy metadata found', { timeout: 30000 });

  await page.locator('#remove-1').click();
  await expect(statusOf(page, 1)).toContainText('Verifying clean output', { timeout: 30000 });

  // ZIP stays disabled while the single item is verifying.
  await expectZipUnavailable(page, 'TEST 6 (single verifying)');

  // No download via real click or synthetic activation.
  await expectNoDownload(page, () => attemptRealClick(page, ZIP_BTN));
  await expectNoDownload(page, () => syntheticActivate(page, ZIP_BTN));

  // Also try the individual download button while it is verifying.
  await expectNoDownload(page, async () => {
    await page.locator('#download-1').click({ force: true }).catch(() => undefined);
  });

  // Defence in depth: invoke the row button's own handler directly, past its
  // `disabled` attribute. downloadItem() must refuse a cleanBlob whose
  // verifyStatus is not yet 'passed'.
  await expectNoDownload(page, async () => {
    await page.evaluate(() => {
      const b = document.querySelector('#download-1') as HTMLButtonElement | null;
      if (b && typeof b.onclick === 'function') (b.onclick as () => void)();
    });
  });

  // Let verification complete -> the single-verified-item path delivers it.
  await expect(page.locator('#download-1')).toBeEnabled({ timeout: 90000 });
  const dlPromise = page.waitForEvent('download', { timeout: 60000 });
  await page.locator('#download-1').click();
  const dl = await dlPromise;
  const saved = join(workDir, 'test6-single.jpg');
  await dl.saveAs(saved);
  const b = readFileSync(saved);
  expect(PRIVACY_VALUES.filter((v) => containsLatin1(b, v))).toEqual([]);
  expect(await privacyKeysInBytes(b, 'image/jpeg')).toEqual([]);

  console.log('TEST 6 PASSED: single-item fallback refused unverified, delivered after pass');
});

// ===========================================================================
// TEST 7 - stale batch: old batch's state never crosses into the new batch.
// ===========================================================================
test('TEST 7 - stale batch: Batch A verification does not affect Batch B', async ({
  page,
}) => {
  test.setTimeout(200000);
  await installDelayHook(page);
  await page.goto(BASE);
  await ensureReady(page);
  await setDelay(page, { needle: NEEDLE, ms: 20000 });

  // Batch A: trailer (held verifying) + clean (will pass)
  await page.locator('#file-input').setInputFiles([trailerJpegPath, cleanJpegPath]);
  await expect(page.locator('#files-list > div[data-id]')).toHaveCount(2, { timeout: 30000 });
  await expect(statusOf(page, 1)).toContainText('Verifying clean output', { timeout: 30000 });
  await page.locator('#remove-2').click();
  await expect(page.locator('#remove-2')).toHaveText(/Success/, { timeout: 60000 });

  // Batch A ZIP must be disabled (item 1 still verifying).
  await expectZipUnavailable(page, 'TEST 7 (Batch A verifying)');

  // --- Stale-batch protection: upload a brand-new Batch B (2 files) ---
  // Two files so Batch B uses the real multi-entry ZIP path, which makes any
  // injected Batch A entry visible in the archive.
  await page.locator('#file-input').setInputFiles([cleanJpegPath2, cleanJpegPath3]);
  await expect(page.locator('#files-list > div[data-id]')).toHaveCount(2, { timeout: 30000 });

  // Batch B items must be fresh: no verifying state, no stale Batch A blob.
  await expect(statusOf(page, 1)).toContainText('Privacy metadata found', { timeout: 30000 });
  await expect(statusOf(page, 2)).toContainText('Privacy metadata found', { timeout: 30000 });

  // Batch B ZIP must be disabled (no outputs yet) - not enabled by Batch A.
  await expectZipUnavailable(page, 'TEST 7 (Batch B fresh, A still verifying)');

  // Process Batch B independently.
  await page.locator('#remove-1').click();
  await expect(page.locator('#download-1')).toBeEnabled({ timeout: 60000 });
  await page.locator('#remove-2').click();
  await expect(page.locator('#download-2')).toBeEnabled({ timeout: 60000 });

  // After Batch B is done, its ZIP must be enabled and contain only verified items.
  await expectZipAvailable(page, 'TEST 7 (Batch B done)');
  const downloadPromise = page.waitForEvent('download', { timeout: 60000 });
  await syntheticActivate(page, ZIP_BTN);
  const zipDownload = await downloadPromise;
  const zipPath = join(workDir, 'test7-stale.zip');
  await zipDownload.saveAs(zipPath);
  const zipBytes = readFileSync(zipPath);

  const JSZip = (await import('jszip')).default;
  const zip = await JSZip.loadAsync(zipBytes);
  const names = Object.keys(zip.files);
  expect(names, 'Batch B ZIP must contain exactly the two Batch B items').toHaveLength(2);
  expect(names.join(' '), 'Batch A must not inject entries into Batch B').not.toContain('trailer');
  expect(names.join(' ')).toContain('gate-two');
  expect(names.join(' ')).toContain('gate-three');

  // The trailer fixture's privacy needle must never leak into Batch B output.
  for (const name of names) {
    const entry = zip.files[name];
    const entryBytes = Buffer.from(await entry.async('uint8array'));
    expect(PRIVACY_VALUES.filter((v) => containsLatin1(entryBytes, v))).toEqual([]);
    expect(await privacyKeysInBytes(entryBytes, 'image/jpeg')).toEqual([]);
  }

  // --- Let Batch A's held verification settle; Batch B must be untouched. ---
  await page.waitForTimeout(22000);
  await expect(
    page.locator('#files-list > div[data-id]'),
    'Batch A must not inject rows into Batch B',
  ).toHaveCount(2);
  await expect(statusOf(page, 1)).toContainText('Metadata removed successfully');
  await expect(statusOf(page, 2)).toContainText('Metadata removed successfully');
  await expect(page.locator('#download-1')).toBeEnabled();
  await expect(page.locator('#download-2')).toBeEnabled();
  await expectZipAvailable(page, 'TEST 7 (Batch B after Batch A settled)');

  console.log('TEST 7 PASSED: Batch A did not affect Batch B ZIP');
});

// ===========================================================================
// TEST 8 - actual ZIP content: only verified items, no privacy leakage.
// ===========================================================================
test('TEST 8 - actual ZIP content: only passed items, no privacy leakage', async ({
  page,
}) => {
  test.setTimeout(120000);
  await page.goto(BASE);
  await ensureReady(page);

  await page.locator('#file-input').setInputFiles([cleanJpegPath, cleanJpegPath2]);
  await expect(page.locator('#files-list > div[data-id]')).toHaveCount(2, { timeout: 30000 });

  await page.locator('#remove-all-btn').click();
  await expect(page.locator('#remove-1')).toHaveText(/Success/, { timeout: 90000 });
  await expect(page.locator('#remove-2')).toHaveText(/Success/, { timeout: 90000 });

  await expectZipAvailable(page, 'TEST 8 (both verified)');

  const downloadPromise = page.waitForEvent('download', { timeout: 60000 });
  await syntheticActivate(page, ZIP_BTN);
  const zipDownload = await downloadPromise;
  const zipPath = join(workDir, 'test8-content.zip');
  await zipDownload.saveAs(zipPath);
  const zipBytes = readFileSync(zipPath);

  const JSZip = (await import('jszip')).default;
  const zip = await JSZip.loadAsync(zipBytes);
  const names = Object.keys(zip.files);
  expect(names, 'ZIP must contain both verified items').toHaveLength(2);

  for (const name of names) {
    const entry = zip.files[name];
    const entryBytes = Buffer.from(await entry.async('uint8array'));
    expect(PRIVACY_VALUES.filter((v) => containsLatin1(entryBytes, v))).toEqual([]);
    expect(await privacyKeysInBytes(entryBytes, 'image/jpeg')).toEqual([]);
  }

  console.log('TEST 8 PASSED: ZIP content verified clean, both items, no privacy leakage');
  console.log('[TEST 8] zip entries:', JSON.stringify(names));
});

// ===========================================================================

// TEST 9 - responsive functional contract (all six viewports), asserted in the
// loop below. The former standalone TEST 9 asserted a deprecated, incorrect
// contract (`hidden` class / visibility "hidden" / display !== "inline-flex").
// Real product behaviour: the control stays rendered and dimmed (Tailwind's
// `hidden` class is overridden by `inline-flex`), but it is genuinely inert -
// `disabled`, `aria-disabled="true"`, not focusable, and clicking it starts no
// download.
// ===========================================================================
// ===========================================================================
// TEST 9 - responsive: ZIP gating observable and enforced at all viewports.
// ===========================================================================
for (const vp of VIEWPORTS) {
  test(`TEST 9 [${vp.label} ${vp.width}x${vp.height}] ZIP inert while a verified item sits beside a verifying one`, async ({
    page,
  }) => {
    test.setTimeout(120000);
    await page.setViewportSize({ width: vp.width, height: vp.height });
    await installDelayHook(page);
    await page.goto(BASE);
    await ensureReady(page);
    await setDelay(page, { needle: NEEDLE, ms: 15000 });

    // Item 1 = trailer -> held open in the 'verifying' window.
    // Item 2 = metadata-bearing JPEG -> removed and verified clean.
    // This is the dangerous state: a verified-clean output really exists, so a
    // gate that tested `cleanBlob` alone would open the control right here.
    await page.locator('#file-input').setInputFiles([trailerJpegPath, cleanJpegPath]);
    await expect(page.locator('#files-list > div[data-id]')).toHaveCount(2, { timeout: 30000 });
    await expect(statusOf(page, 1)).toContainText('Verifying clean output', { timeout: 30000 });

    await page.locator('#remove-2').click();
    await expect(page.locator('#download-2')).toBeEnabled({ timeout: 60000 });

    // Positive control: a verified-clean item really does exist right now.
    await expectZipUnavailable(page, `TEST 9 [${vp.label}] 1 verified + 1 verifying`);

    // Functional contract: genuinely inert, not merely styled.
    const probe = await page.evaluate(() => {
      const b = document.querySelector('#download-all-btn') as HTMLButtonElement | null;
      if (!b) return { missing: true };
      b.focus();
      return {
        missing: false,
        disabled: b.disabled,
        ariaDisabled: b.getAttribute('aria-disabled'),
        focusable: document.activeElement === b,
      };
    });
    expect(probe.missing, 'button must exist').toBe(false);
    expect(probe.disabled, `TEST 9 [${vp.label}] button must be disabled`).toBe(true);
    expect(probe.ariaDisabled, `TEST 9 [${vp.label}] aria-disabled must be true`).toBe('true');
    expect(probe.focusable, `TEST 9 [${vp.label}] disabled control must not be focusable`).toBe(false);

    // A real click must start no download at all.
    await expectNoDownload(page, () => attemptRealClick(page, ZIP_BTN));

    console.log(
      `TEST 9 [${vp.label}] PASSED: ZIP inert (disabled + aria-disabled + not focusable + no download) at ${vp.width}x${vp.height}`,
    );
  });
}
